#> gun_501:spread/wobble
#
# Generated by MCF-Utility
#
# @within function player_501:get_wobble

function gun_501:spread/set
function gun_501:spread/circle

execute as 0-0-1f5-0-0 at @s run function gun_501:spread/get_facing