#> reversi_201:menu/hologram_collider
#
# Generated by MCF-Utility
#
# @private

summon minecraft:slime 2066.2 240.2 38.8 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2068.8 240.2 38.8 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2069.2 240.2 38.8 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2071.8 240.2 38.8 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}

summon minecraft:slime 2066.2 240.2 36.2 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2068.8 240.2 36.2 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2069.2 240.2 36.2 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2071.8 240.2 36.2 {Tags:[hologram_sandbag_001,hologram_sandbag_201.menu],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}

summon minecraft:slime 2052.5 240.2 31.6 {Tags:[hologram_sandbag_001,hologram_sandbag_201.area],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
summon minecraft:slime 2053.5 240.2 31.6 {Tags:[hologram_sandbag_001,hologram_sandbag_201.area],Size:4,NoAI:1b,Silent:1b,PersistenceRequired:1b,Team:"NoCollision_201",ActiveEffects:[{Id:14,Amplifier:0b,Duration:19999980,ShowParticles:0b},{Id:11,Amplifier:4b,Duration:19999980,ShowParticles:0b}]}
execute as @e[type=slime,tag=hologram_sandbag_201.menu,distance=..200,x=2069.0,y=40.0,z=21.0] at @s run tp ~ ~-200 ~
execute as @e[type=slime,tag=hologram_sandbag_201.menu,distance=..200,x=2069.0,y=240.0,z=21.0] at @s run tp ~ ~-200 ~
execute as @e[type=slime,tag=hologram_sandbag_201.area,distance=..200,x=2069.0,y=40.0,z=21.0] at @s run tp ~ ~-200 ~
execute as @e[type=slime,tag=hologram_sandbag_201.area,distance=..200,x=2069.0,y=240.0,z=21.0] at @s run tp ~ ~-200 ~