#> reversi_201:menu/hologram_collider
#
# Generated by MCF-Utility
#
# @private

kill @e[type=interaction,tag=hologram_sandbag_201.menu,distance=..200,x=2069.0,y=40.0,z=21.0]
kill @e[type=interaction,tag=hologram_sandbag_201.area,distance=..200,x=2069.0,y=40.0,z=21.0]

summon minecraft:interaction 2069.0 39.0 36.0 {height:5.0f,width:8.0f,Tags:["hologram_sandbag_001","hologram_sandbag_201.menu"]}
summon minecraft:interaction 2053.0 39.5 30.0 {height:7.0f,width:6.0f,Tags:["hologram_sandbag_001","hologram_sandbag_201.area"]}