#> reversi_201:menu/select_handler
#
# Generated by MCF-Utility
#
# @within tag/function minecraft:handler/001_hologram.select

execute if score @s hologram_id_001 matches 2000..2099 run function reversi_201:menu/select