#> reversi_201:game/turn/player/long_think/end
#
# Generated by MCF-Utility
#
# @within function reversi_201:game/turn/select

schedule clear reversi_201:game/turn/player/long_think/decrement
execute if score #TurnColor ReversiData_201 matches 0 if score #Think.Flag.Black ReversiData_201 matches 1 store result bossbar reversi_201:player1_201 value store result bossbar reversi_201:player1_201 max run scoreboard players operation #Think.Black ReversiData_201 = $Think.COUNT ReversiData_201
execute if score #TurnColor ReversiData_201 matches 1 if score #Think.Flag.White ReversiData_201 matches 1 store result bossbar reversi_201:player2_201 value store result bossbar reversi_201:player2_201 max run scoreboard players operation #Think.White ReversiData_201 = $Think.COUNT ReversiData_201