#> bullet_501:hit/fluid/water
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/hit/material/fluid

execute unless score #IN num_501 matches 2 run function bullet_501:in/water/enter
scoreboard players set @s in_501 2