#> reversi_201:menu/area_linker/action.holo_create
#
# Generated by MCF-Utility
#
# @private

summon armor_stand 2053.0 37.75053710937 30.0 {Tags:["WelcomeMat_201"],ArmorItems:[{},{},{},{id:"minecraft:green_concrete",Count:1b,tag:{CustomModelData:2000}}],DisabledSlots:4144959,Invisible:1b,NoGravity:1b}
data modify storage utility_001:hologram_util TextGroup set value [{Offset:[0f,0f],Setting:{CursorCollider:1b,TextInterpret:0b,TextSpaceWidth:0.25f},HologramID:2099,Text:['ロ','ビ','ー','へ']}]
execute positioned 2053.375 41.2 32.75 rotated 90 0 run function utility_001:hologram_util/api/create