#> reversi_201:menu/area_linker/join
#
# Generated by MCF-Utility
#
# @private

scoreboard players set @s playing_000 201
function player_000:join_game
scoreboard players set @s food_000 21
tp @s 2053.0 39.6 30.0 180 0