#> reversi_201:menu/area_linker/leave
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:menu/action/_area.leave
#   reversi_201:menu/action/_area.leave

tag @s remove hologram_operator_001
tag @s remove Player_White_201
tag @s remove Player_Black_201
execute if entity @e[type=armor_stand,tag=hologram.overlay.0_201,distance=..0.0001,x=2070.37,y=41.1,z=38.8] run function reversi_201:menu/action/main._overlay
function player_000:leave_game

execute if score $isPlay ReversiData_201 matches 1 if score #Think ReversiData_201 matches 1 unless score $vsAI ReversiData_201 matches 0 run bossbar set reversi_201:player1_201 players @a[scores={playing_000=201}]
execute if score $isPlay ReversiData_201 matches 1 if score #Think ReversiData_201 matches 1 unless score $vsAI ReversiData_201 matches 1 run bossbar set reversi_201:player2_201 players @a[scores={playing_000=201}]