#> reversi_201:menu/area_linker/leave
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:menu/action/_area.leave
#   reversi_201:menu/action/_area.leave

tag @s remove hologram_operator_001
tag @s remove Player_White_201
tag @s remove Player_Black_201
function reversi_201:menu/action/main._overlay
function player_000:leave_game