#> bullet_501:detailed/block/stairs/root
#
# Generated by MCF-Utility
#
# @within tag/function bullet_501:detailed/block/stairs

execute store result score #0 property_501 if predicate bullet_501:detailed/stairs/0
execute store result score #1 property_501 if predicate bullet_501:detailed/stairs/1
execute store result score #2 property_501 if predicate bullet_501:detailed/stairs/2
execute store result score #3 property_501 if predicate bullet_501:detailed/stairs/3

function bullet_501:detailed/block/stairs/loop