#> reversi_201:game/stone/util/init_put
#
# Generated by MCF-Utility
#
# @within function reversi_201:game/start.common

summon armor_stand 2069 38.6 20 {ArmorItems:[{},{},{},{id:"minecraft:white_concrete",Count:1b,tag:{CustomModelData:0}}],Tags:[stone_201,Entity_201],NoGravity:1b,Invisible:1b,Invulnerable:1b}
execute store result entity @e[type=armor_stand,tag=stone_201,distance=..0.05,x=2069.5,y=38.6,z=20.5,limit=1] ArmorItems[3].tag.CustomModelData int 1 run scoreboard players get #CurrentSkin StoneSkin_201
summon armor_stand 2069 38.6 21 {ArmorItems:[{},{},{},{id:"minecraft:black_concrete",Count:1b,tag:{CustomModelData:0}}],Tags:[stone_201,Entity_201],NoGravity:1b,Invisible:1b,Invulnerable:1b}
execute store result entity @e[type=armor_stand,tag=stone_201,distance=..0.05,x=2069.5,y=38.6,z=21.5,limit=1] ArmorItems[3].tag.CustomModelData int 1 run scoreboard players get #CurrentSkin StoneSkin_201
summon armor_stand 2068 38.6 20 {ArmorItems:[{},{},{},{id:"minecraft:black_concrete",Count:1b,tag:{CustomModelData:0}}],Tags:[stone_201,Entity_201],NoGravity:1b,Invisible:1b,Invulnerable:1b}
execute store result entity @e[type=armor_stand,tag=stone_201,distance=..0.05,x=2068.5,y=38.6,z=20.5,limit=1] ArmorItems[3].tag.CustomModelData int 1 run scoreboard players get #CurrentSkin StoneSkin_201
summon armor_stand 2068 38.6 21 {ArmorItems:[{},{},{},{id:"minecraft:white_concrete",Count:1b,tag:{CustomModelData:0}}],Tags:[stone_201,Entity_201],NoGravity:1b,Invisible:1b,Invulnerable:1b}
execute store result entity @e[type=armor_stand,tag=stone_201,distance=..0.05,x=2068.5,y=38.6,z=21.5,limit=1] ArmorItems[3].tag.CustomModelData int 1 run scoreboard players get #CurrentSkin StoneSkin_201