#> bullet_501:gap/initialize
#
# Generated by MCF-Utility
#
# @within tag/function
#   bullet_501:gap/z
#   bullet_501:gap/y
#   bullet_501:gap/x

#execute store result score #detailed x_vec_501 run scoreboard players operation #x num_501 = #x ope_501
#execute store result score #detailed y_vec_501 run scoreboard players operation #y num_501 = #y ope_501
#execute store result score #detailed z_vec_501 run scoreboard players operation #z num_501 = #z ope_501
scoreboard players operation #detailed x_vec_501 = #x ope_501
scoreboard players operation #detailed y_vec_501 = #y ope_501
scoreboard players operation #detailed z_vec_501 = #z ope_501
scoreboard players set #X pos_501 0
scoreboard players set #Y pos_501 0
scoreboard players set #Z pos_501 0