#> bullet_501:detailed/hit/finish
#
# Generated by MCF-Utility
#
# @within tag/function
#   bullet_501:detailed/hit/planks/oak
#   bullet_501:detailed/hit/planks/dark_oak
#   bullet_501:detailed/hit/others
#   bullet_501:detailed/hit/metal
#   bullet_501:detailed/hit/fluid
#   bullet_501:detailed/hit/dirt
#   bullet_501:detailed/hit

execute store result entity @s Pos[0] double 0.0001 run scoreboard players get #x pos_501
execute store result entity @s Pos[1] double 0.0001 run scoreboard players get #y pos_501
execute store result entity @s Pos[2] double 0.0001 run scoreboard players get #z pos_501