#> bullet_501:detailed/hit/stop
#
# Generated by MCF-Utility
#
# @within tag/function bullet_501:detailed/hit

execute unless block ~ ~ ~ #bullet_501:penetratable run function bullet_501:detailed/stop