#> reversi_201:game/stone/sheep/reput
#
# Generated by MCF-Utility
#
# @within function reversi_201:game/stone/check

summon minecraft:area_effect_cloud ~ ~ ~ {Age:-2147483648,Duration:-1,WaitTime:-2147483648,Tags:[temP]}
execute store result score $Current SheepID_X_201 run data get entity @e[type=area_effect_cloud,tag=temP,distance=..200,x=2069.0,y=40.0,z=21.0,limit=1] Pos[0] 10
execute store result score $Current SheepID_Y_201 run data get entity @e[type=area_effect_cloud,tag=temP,distance=..200,x=2069.0,y=40.0,z=21.0,limit=1] Pos[2] 10
kill @e[type=area_effect_cloud,tag=temP,distance=..200,x=2069.0,y=40.0,z=21.0,limit=1]
execute as @e[type=sheep,tag=StoneSheep_201,distance=..200,x=2069.0,y=40.0,z=21.0] if score $Current SheepID_X_201 = @s SheepID_X_201 if score $Current SheepID_Y_201 = @s SheepID_Y_201 run tp @s ~ 40.6 ~
execute as @e[type=sheep,tag=StoneSheep_201,distance=..200,x=2069.0,y=40.0,z=21.0] if score $Current SheepID_X_201 = @s SheepID_X_201 if score $Current SheepID_Y_201 = @s SheepID_Y_201 run data modify entity @s Motion[1] set value 0.3d
execute if score #TurnColor ReversiData_201 matches 0 as @e[type=sheep,tag=StoneSheep_201,distance=..200,x=2069.0,y=40.0,z=21.0] if score $Current SheepID_X_201 = @s SheepID_X_201 if score $Current SheepID_Y_201 = @s SheepID_Y_201 run data modify entity @s Color set value 15b
execute if score #TurnColor ReversiData_201 matches 1 as @e[type=sheep,tag=StoneSheep_201,distance=..200,x=2069.0,y=40.0,z=21.0] if score $Current SheepID_X_201 = @s SheepID_X_201 if score $Current SheepID_Y_201 = @s SheepID_Y_201 run data modify entity @s Color set value 0b