#> reversi_201:game/turn/common/sort.duplicated_shift
#
# Generated by MCF-Utility
#
# @within function reversi_201:game/turn/common/sort.run

execute if score @s SortValue_201 = @e[type=area_effect_cloud,tag=Candidate_201,tag=!InactiveCandidate_201,sort=nearest,limit=1] SortValue_201 unless entity @s[distance=..0.01] run scoreboard players add @s SortValue_201 1