#> minecraft:debug/block_particle
#
# Generated by MCF-Utility
#
# @private

particle end_rod ~00.50 ~0 ~00.50 0 0 0 0 1
particle end_rod ~00.50 ~0 ~00.16 0 0 0 0 1
particle end_rod ~00.50 ~0 ~-0.16 0 0 0 0 1
particle end_rod ~00.50 ~0 ~-0.50 0 0 0 0 1
particle end_rod ~00.16 ~0 ~-0.50 0 0 0 0 1
particle end_rod ~-0.16 ~0 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~0 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~0 ~-0.16 0 0 0 0 1
particle end_rod ~-0.50 ~0 ~00.16 0 0 0 0 1
particle end_rod ~-0.50 ~0 ~00.50 0 0 0 0 1
particle end_rod ~-0.16 ~0 ~00.50 0 0 0 0 1
particle end_rod ~00.16 ~0 ~00.50 0 0 0 0 1

particle end_rod ~00.50 ~0.33 ~00.50 0 0 0 0 1
particle end_rod ~00.50 ~0.66 ~00.50 0 0 0 0 1
particle end_rod ~00.50 ~0.33 ~-0.50 0 0 0 0 1
particle end_rod ~00.50 ~0.66 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~0.33 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~0.66 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~0.33 ~00.50 0 0 0 0 1
particle end_rod ~-0.50 ~0.66 ~00.50 0 0 0 0 1

particle end_rod ~00.50 ~1 ~00.50 0 0 0 0 1
particle end_rod ~00.50 ~1 ~00.16 0 0 0 0 1
particle end_rod ~00.50 ~1 ~-0.16 0 0 0 0 1
particle end_rod ~00.50 ~1 ~-0.50 0 0 0 0 1
particle end_rod ~00.16 ~1 ~-0.50 0 0 0 0 1
particle end_rod ~-0.16 ~1 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~1 ~-0.50 0 0 0 0 1
particle end_rod ~-0.50 ~1 ~-0.16 0 0 0 0 1
particle end_rod ~-0.50 ~1 ~00.16 0 0 0 0 1
particle end_rod ~-0.50 ~1 ~00.50 0 0 0 0 1
particle end_rod ~-0.16 ~1 ~00.50 0 0 0 0 1
particle end_rod ~00.16 ~1 ~00.50 0 0 0 0 1