#> bullet_501:detailed/hit/material/fluid
#
# Generated by MCF-Utility
#
# @within tag/function bullet_501:detailed/hit/fluid

execute if predicate bullet_501:fluid/water positioned as @s run function bullet_501:hit/fluid/water

execute if predicate bullet_501:fluid/lava run function bullet_501:detailed/stop
execute if predicate bullet_501:fluid/lava positioned as @s run function bullet_501:hit/fluid/lava