#> bullet_501:detailed/hit/material/metal
#
# Generated by MCF-Utility
#
# @within tag/function bullet_501:detailed/hit/metal

execute positioned as @s run function bullet_501:hit/block/material/metal

#execute if score #HITMARK num_501 matches 1 if score #HITMARK ope_501 < #HITMARK_MAX num_501 positioned as @s run function bullet_501:hit/block/mark