#> bullet_501:detailed/block/fence_gates/root
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/root

execute if block ~ ~ ~ #bullet_501:fence_gates[in_wall=false] run function bullet_501:detailed/block/fence_gates/default/loop
execute if block ~ ~ ~ #bullet_501:fence_gates[in_wall=true] run function bullet_501:detailed/block/fence_gates/in_wall/loop