#> bullet_501:hit/block/marked
#
# Generated by MCF-Utility
#
# @within function bullet_501:hit/block/mark

scoreboard players add #HITMARK ope_501 1
loot replace entity @s armor.head loot bullet_501:hit_mark
stopsound @a[distance=..16] neutral item.armor.equip_generic
tag @s remove summoning_501