#> reversi_201:game/debug/log.output
#
# Generated by MCF-Utility
#
# @private

data modify storage reversi_201:logs out set from storage reversi_201:logs output
function reversi_201:game/debug/log.output.recursive