#> reversi_201:game/debug/log.output.recursive
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:game/debug/log.output.recursive
#   reversi_201:game/debug/log.output

tellraw @a[scores={playing_000=201}] [{"storage":"reversi_201:logs","nbt":"out[0].active_still","color":"blue","italic":false},{"text":" / ","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].active_already","color":"blue","italic":false},{"text":" / ","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].inactive_still","color":"blue","italic":false},{"text":" / ","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].inactive_already","color":"blue","italic":false},{"text":" | T:","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].TickThroughputC","color":"aqua","italic":false},{"text":", R:","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].RemainingDepth","color":"gold","italic":false},{"text":", M:","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].MoreDepthTurnColor","color":"light_purple","italic":false},{"text":" | ","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].StoneQuantity","color":"green","italic":false},{"text":"-","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].logScore","color":"green","italic":false},{"text":" / ","color":"white","italic":false},{"storage":"reversi_201:logs","nbt":"out[0].functionName","color":"green","italic":false}]
data remove storage reversi_201:logs out[0]
execute if data storage reversi_201:logs out[] run function reversi_201:game/debug/log.output.recursive