#> reversi_201:game/turn/ai/search.success
#
# Generated by MCF-Utility
#
# @within function reversi_201:game/turn/ai/search.recursive.run

# 候補のEntity召喚する
    summon area_effect_cloud ~ ~ ~ {Rotation:[0f,90f],Age:-2147483648,Duration:-1,WaitTime:-2147483648,Tags:["Candidate_201","Entity_201"]}
# 49手以降の検査
    #execute if score #StoneQuantity ReversiData_201 matches 49.. if score #StoneQuantity ReversiData_201 < #AI-LastAlgorithm ReversiData_201 run function reversi_201:game/turn/ai/algorithm/2nd.run
# 評価値の設定 63-n手目以降は0が入る
    scoreboard players operation @e[type=area_effect_cloud,tag=Candidate_201,distance=..0.5] Evaluation_201 = #Tmp Evaluation_201
# 4隅の補正入れる
    execute if score #StoneQuantity ReversiData_201 < #AI-LastAlgorithm ReversiData_201 as @e[type=area_effect_cloud,tag=Candidate_201,distance=..0.5] at @s run function reversi_201:game/turn/ai/eval_modifier
# リセット
    scoreboard players set #Tmp Evaluation_201 0