#> gun_501:animation/action/reload/cancel
#
# Generated by MCF-Utility
#
# @within function gun_501:animation/action/reload/check

function gun_501:animation/action/reload/finish
function gun_501:animation/replace