#> gun_501:animation/action/reload/load
#
# Generated by MCF-Utility
#
# @within function gun_501:animation/action

execute if data storage gun_501:temp tag.gun.mag.mag{Count:0b} run function gun_501:animation/action/reload/ammo/root