#> reversi_201:game/start
#
# Generated by MCF-Utility
#
# @within function reversi_201:menu/action/main.start

# 開始
    function reversi_201:game/start.common
    schedule function reversi_201:game/turn/turn_checker 1s