#> bullet_501:detailed/stop
#
# Generated by MCF-Utility
#
# @within
#   function
#       bullet_501:detailed/hit/material/fluid
#       bullet_501:detailed/hit/stop
#   tag/function
#       bullet_501:detailed/hit/planks/oak
#       bullet_501:detailed/hit/planks/dark_oak
#       bullet_501:detailed/hit/others
#       bullet_501:detailed/hit/metal
#       bullet_501:detailed/hit/dirt

scoreboard players operation #min num_501 = #BASE num_501
scoreboard players set #SPEED num_501 0
scoreboard players set #SKIP num_501 0
scoreboard players add #HIT num_501 1