#> reversi_201:game/turn/player/cursor.move
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:game/turn/player/search.end
#   reversi_201:game/force_end

execute as @e[tag=NoVisible_201,distance=..200,x=2069.0,y=40.0,z=21.0] at @s run tp @s ~ ~11.5 ~