#> reversi_201:game/turn/player/search.recursive.manager
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:game/turn/player/search.recursive.run
#   reversi_201:game/turn/turn_checker
#   reversi_201:game/force_end

scoreboard players operation #TickThroughputC ReversiData_201 = $TickThroughput ReversiData_201
execute as 0-0-c9-0-0 at @s run function reversi_201:game/turn/player/search.recursive.run