#> reversi_201:game/turn/select_non_player
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:game/turn/ai/advanced/lv_branch
#   reversi_201:game/turn/ai/advanced/deep.back
#   reversi_201:game/force_end

    # #DEBUG log
    # data merge storage reversi_201:logs {tmp:"reversi_201:game/turn/ai/advanced/deep.back"}
    # function reversi_201:game/debug/log.put
# 決定時の処理
    execute at @e[type=area_effect_cloud,tag=Candidate_201,distance=..50,x=-19995.0,y=11.0,z=21.0] run particle totem_of_undying ~22064 42 ~ 0 0.5 0 0 40
    execute as @e[type=area_effect_cloud,tag=Candidate_201,distance=..50,x=-19995.0,y=11.0,z=21.0] at @s align xyz positioned ~0.5 10 ~0.5 run function reversi_201:game/stone/set