#> bullet_501:hit/entity
#
# Generated by MCF-Utility
#
# @within tag/function gun_501:hit_entity

execute if entity @s[type=player] run function bullet_501:hit/entity/player
execute if entity @s[tag=enemy_501] run function bullet_501:hit/entity/enemy
execute if entity @s[tag=check_501] run function bullet_501:hit/entity/check
#execute if entity @s[type=item,tag=clay_502] at @s run function clay_502:hit