#> bullet_501:detailed/block/piston/east
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/piston/loop

scoreboard players set #x max_501 7500
scoreboard players set #x min_501 0
scoreboard players set #y max_501 10000
scoreboard players set #y min_501 0
scoreboard players set #z max_501 10000
scoreboard players set #z min_501 0
function #bullet_501:detailed/hit