#> bullet_501:detailed/block/piston/root
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/root

execute if block ~ ~ ~ #bullet_501:piston[extended=false] run scoreboard players set #type property_501 -1
function #bullet_501:detailed/block/piston