#> bullet_501:particle
#
# Generated by MCF-Utility
#
# @within function bullet_501:skip

execute if score @s in_501 matches 2 run particle bubble ~ ~ ~ 0 0 0 0 2 force @a
execute if score #PARTICLE num_501 matches 0 run particle minecraft:dust 0.25 0.25 0.25 0.33 ~ ~ ~ 0 0 0 0 0 force @a
execute if score #PARTICLE num_501 matches 1 run particle minecraft:dust 10000000000000000 0.25 0.25 0.33 ~ ~ ~ 0 0 0 0 0 force @a