#> bullet_501:rescale
#
# Generated by MCF-Utility
#
# @within function bullet_501:root

scoreboard players operation #BULLET x_vec_501 /= #SCALE num_501
scoreboard players operation #BULLET y_vec_501 /= #SCALE num_501
scoreboard players operation #BULLET z_vec_501 /= #SCALE num_501
scoreboard players operation #SPEED num_501 *= #SCALE num_501