#> bullet_501:spread
#
# Generated by MCF-Utility
#
# @within function bullet_501:shot

function gun_501:spread/circle

execute store result score @s x_vec_501 run scoreboard players operation #X spread_501 /= #1000000 num_000
execute store result score @s y_vec_501 run scoreboard players operation #Y spread_501 /= #1000000 num_000
execute store result score @s z_vec_501 run scoreboard players operation #Z spread_501 /= #1000000 num_000