#> bullet_501:in/water/skip
#
# Generated by MCF-Utility
#
# @within function bullet_501:skip

#scoreboard players operation @s speed_501 *= #BREAKABLE ope_501
#scoreboard players operation @s speed_501 /= #100 num_000
#scoreboard players operation @s speed_501 > #1 num_000

#particle bubble ~ ~ ~ 0 0 0 0 2 force @a