#> reversi_201:rejoin_handler
#
# Generated by MCF-Utility
#
# @within tag/function minecraft:handler/000_login

execute if entity @a[scores={playing_000=201},distance=..200,x=2069.0,y=40.0,z=21.0] run function reversi_201:rejoin