#> reversi_201:second
#
# Generated by MCF-Utility
#
# @within tag/function minecraft:second

execute if score $isPlay ReversiData_201 matches 1 if score #PlayTime ReversiData_201 matches ..599 run scoreboard players add #PlayTime ReversiData_201 1