#> bullet_501:hit/block/material/soft
#
# Generated by MCF-Utility
#
# @within function
#   bullet_501:hit/block/root
#   bullet_501:hit/block

playsound minecraft:block.wool.hit block @a ~ ~ ~ 0.25 1 0
playsound minecraft:block.fire.extinguish block @a ~ ~ ~ 0.05 2 0
summon area_effect_cloud ~ ~ ~ {Radius:0.0f,Tags:["sound_501","soft_501"]}