#> bullet_501:detailed/block/trapdoors/bottom
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/trapdoors/root

scoreboard players set #y max_501 1250
scoreboard players set #y min_501 0
function #bullet_501:detailed/hit