#> bullet_501:detailed/block/trapdoors/north
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/trapdoors/open

scoreboard players set #x max_501 10000
scoreboard players set #x min_501 0
scoreboard players set #z max_501 10000
scoreboard players set #z min_501 8750
function #bullet_501:detailed/hit