#> bullet_501:detailed/block/trapdoors/top
#
# Generated by MCF-Utility
#
# @within function bullet_501:detailed/block/trapdoors/root

scoreboard players set #y max_501 10000
scoreboard players set #y min_501 8750
function #bullet_501:detailed/hit