#> gun_501:chamber/shot
#
# Generated by MCF-Utility
#
# @within function gun_501:animation/shot

data remove storage gun_501:temp tag.gun.chamber.tag.ammo.bullet

data modify storage gun_501:temp tag.gun.amount set from storage gun_501:temp tag.gun.mag.mag.tag.mag.amount