#> reversi_201:game/end/end.common2
#
# Generated by MCF-Utility
#
# @within function
#   reversi_201:game/end/end.common
#   reversi_201:game/end/end.common

# 隔離終了
    fill 2056 43 23 2056 40 18 air
    fill 2081 40 23 2081 43 18 air
# メニュー復活
    function reversi_201:menu/action/common.main